SWPBL-188127 -- Window management and block info display
jehan-diaz/imnodes pull request #10
Opened 2022-07-25 18:46 UTC by jehan-diaz

When a user clicks on a block, the list of attributes and their values for that block type must be displayed. These attributes, which for now include pre-set and standardized attributes for each block, can be seen in the multi-purpose panel when hovering over a block.

Right now, we are able to see two panels in the same main app window view at the same time. We are now also able to scan over the enter central editor using the minimap, which allows you to select a node to focus into the center of the editor.

2022-07-25 20:55 UTC, EvanShenkman-Sonos requested changes
Couldn't get it to compile. Make some small quick fixes and I'll take a closer look once I can build it.

2022-07-25 20:55 UTC, EvanShenkman-Sonos commented on example/Dynamite/editor.h
> +    static void Editor::init() {
This should be `static void init()`

I'm surprised that this compiles for you. Are you using Visual Studio?

2022-07-25 20:55 UTC, EvanShenkman-Sonos commented on example/Dynamite/editor.h
> +    static void Editor::exit() {
Same comment here, drop `Editor::`

2022-07-25 20:55 UTC, EvanShenkman-Sonos commented on example/Dynamite/multipanel.cpp
> +#pragma once
Delete this line. You don't need this in a source file.

2022-07-25 21:39 UTC, jehan-diaz commented on example/Dynamite/editor.h
> +    static void Editor::init() {
Unclear but I think it has to do with what version of C++ Visual Studio (not VS Code, which is what I and Kevin) uses. Visual Studio is apparently Microsoft specific

2022-07-26 14:24 UTC, KevinKimSonos commented
Seeing a weird behavior where if I create multiple nodes and right click one of the nodes, I see multiple "Bypass" and "Other options
<img width="759" alt="Screen Shot 2022-07-26 at 10 15 39 AM" src="https://user-images.githubusercontent.com/107052172/181030671-3a6f3abd-c431-4a71-ab80-eda151c980fa.png">
"

2022-07-26 14:53 UTC, EvanShenkman-Sonos commented
> Seeing a weird behavior where if I create multiple nodes and right click one of the nodes, I see multiple "Bypass" and "Other options <img alt="Screen Shot 2022-07-26 at 10 15 39 AM" width="759" src="https://user-images.githubusercontent.com/107052172/181030671-3a6f3abd-c431-4a71-ab80-eda151c980fa.png"> "

Two things here:

1. We're generally _**not**_ allowed to upload images to GitHub. It's not a huge deal for this project, however GitHub stores the images publicly and it's an easy way for confidential info to leak.

2. I don't see this behavior. I've added many blocks and right clicking on each of them only show Bypass and Other.

2022-07-26 14:58 UTC, EvanShenkman-Sonos approved these changes

2022-07-26 15:02 UTC, KevinKimSonos commented
> > Seeing a weird behavior where if I create multiple nodes and right click one of the nodes, I see multiple "Bypass" and "Other options <img alt="Screen Shot 2022-07-26 at 10 15 39 AM" width="759" src="https://user-images.githubusercontent.com/107052172/181030671-3a6f3abd-c431-4a71-ab80-eda151c980fa.png"> "
> 
> Two things here:
> 
> 1. We're generally _**not**_ allowed to upload images to GitHub. It's not a huge deal for this project, however GitHub stores the images publicly and it's an easy way for confidential info to leak.
> 2. I don't see this behavior. I've added many blocks and right clicking on each of them only show Bypass and Other.

Thanks for letting me know about this. I will not upload images to GitHub in the future.

2022-07-26 17:31 UTC, merged